package com.forteanuncio.prep.dadospublicoscnpj.constants;

public final class FieldsModels{
    public static final String[] EMPRESA = {
        "cnpj",
        "matriz",
        "razaoSocial",
        "nomeFantasia",
        "situacaoCadastral",
        "dataSituacaoCadastral",
        "codigoMotivoSitualCadastral",
        "nomeCidadeExterior",
        "codigoPais",
        "nomePais",
        "codigoNaturezaJuridica",
        "dataInicioAtividade",
        "cnaeFiscal",
        "descLogradouro",
        "logradouro",
        "numero",
        "complemento",
        "bairro",
        "cep",
        "uf",
        "codigoMunicipio",
        "municipio",
        "ddd1",
        "telefone1",
        "ddd2",
        "telefone2",
        "dddFax",
        "numFax",
        "email",
        "qualificacaoResponsavel",
        "capitalSocial",
        "porteEmpresa",
        "opcaoPeloSimplesNacional",
        "dataOpcaoPeloSimplesNacional",
        "dataExclusaoSimplesNacional",
        "opcaoPeloMei",
        "situacaoEspecial",
        "dataSituacaoEspecial",
        "dataHoraInsercao"
    };
}